apiVersion: v1
kind: ReplicationController
metadata:
  name: gaiad
spec:
  replicas: 1
  selector:
    name: gaiad
  template:
    metadata:
      labels:
        name: gaiad
    spec:
      containers:
      - image: "dockerhubimageName"
        imagePullPolicy: IfNotPresent
        name: gaiad
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/opt/share/"
      volumes:
      - name: nfs
        hostPath:
          path: /opt/share/
      # - name: nfs
        # persistentVolumeClaim:
        #   claimName: nfs
          
