apiVersion: v1
kind: ReplicationController
metadata:
  name: gaiad
spec:
  replicas: 1
  selector:
    name: gaiad
  template:
    metadata:
      labels:
        name: gaiad
    spec:
      containers:
      - image: golang:latest
        command:
          - go get -u -v github.com/fatih/color 
          - cd /go/src/github.com 
          - mkdir cosmos 
          - cd cosmos 
          - git clone https://github.com/cosmos/cosmos-sdk.git 
          - cd cosmos-sdk 
          - make get_tools && make get_vendor_deps && make install 
        imagePullPolicy: IfNotPresent
        name: gaiad
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/opt/share/"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
